# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-05-03 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='exploit_cve',
            field=models.CharField(default=b'no', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='exploit_name',
            field=models.CharField(default=b'no', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='exploit_port',
            field=models.CharField(default=b'no', max_length=255),
        ),
    ]
