# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-05-04 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_auto_20200503_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exploiated_sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_number', models.CharField(max_length=255)),
                ('exploit_name', models.CharField(max_length=255)),
                ('payload_name', models.CharField(max_length=255)),
                ('session_id', models.CharField(default=b'no_session', max_length=255)),
                ('host_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='exploit_cve',
        ),
        migrations.RemoveField(
            model_name='job',
            name='exploit_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='exploit_port',
        ),
    ]
