# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-05-04 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_auto_20200504_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exploiated_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('cve_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('exploit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payload_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('host_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Exploiated_sys',
        ),
    ]
