# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-05-04 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_auto_20200504_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_exploit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_host_name', models.CharField(max_length=255)),
                ('config_host_id', models.CharField(max_length=255)),
                ('config_cve_number', models.CharField(blank=True, max_length=255, null=True)),
                ('config_exploit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('config_payload_name', models.CharField(blank=True, max_length=255, null=True)),
                ('config_rhost', models.CharField(blank=True, max_length=255, null=True)),
                ('config_rport', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='exploit_status',
            field=models.CharField(default=b'Exploit', max_length=255),
        ),
    ]
