# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-05-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0011_job_exploit_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSF_rpc_connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpc_uname', models.CharField(max_length=255)),
                ('rpc_pass', models.CharField(max_length=255)),
                ('rpc_ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='openvas_connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opv_uname', models.CharField(max_length=255)),
                ('opv_pass', models.CharField(max_length=255)),
                ('opv_ip', models.CharField(max_length=255)),
            ],
        ),
    ]
