# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-05-11 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0012_msf_rpc_connection_openvas_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='opv_report_id',
            field=models.CharField(default=b'no', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='opv_scan_id',
            field=models.CharField(default=b'no', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='opv_target_id',
            field=models.CharField(default=b'no', max_length=255),
        ),
    ]
